### ISSUE TITLE
gem conflict. 

### ISSUE THREAD

**Issue by zw963** [christopheraue/ruby-uinput-device#1]
I just want to try following snippets code in README.md

``` ruby
#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'uinput/device'

device = Uinput::Device.new do
  self.name = 'Our virtual device'
  self.type = LinuxInput::BUS_VIRTUAL

  add_key(:KEY_A)
  add_event(:EV_KEY)
  add_event(:EV_SYN)
end

device.send_event(:EV_KEY, :KEY_A, 1)
device.send_event(:EV_SYN, :SYN_REPORT)

# key up
device.send_event(:EV_KEY, :KEY_A, 0)
device.send_event(:EV_SYN, :SYN_REPORT)

```

But seem like got gem conflict.

``` sh
/home/zw963/.rvm/gems/ruby-2.2.4@uinput1/gems/uinput-device-0.3.2/lib/uinput/device/system_initializer.rb:7:in `initialize': uninitialized constant LinuxInput::Uinput::Device::SystemInitializer::Fcntl (NameError)
    from /home/zw963/.rvm/gems/ruby-2.2.4@uinput1/gems/uinput-device-0.3.2/lib/uinput/device.rb:12:in `new'
    from /home/zw963/.rvm/gems/ruby-2.2.4@uinput1/gems/uinput-device-0.3.2/lib/uinput/device.rb:12:in `initialize'
    from test.rb:6:in `new'
    from test.rb:6:in `<main>'
```

I thought those code is dangerous 
https://github.com/christopheraue/ruby-uinput/blob/master/lib/uinput.rb#L6

perhaps should merge `linux_uinput` and `uinput` into one gem.

**Comment by christopheraue** [comment]
Fixed in https://github.com/christopheraue/ruby-uinput-device/commit/b266e68b5027dd859aa4fb7b189afb3c5b6ad670

**Comment by zw963** [comment]
it worked. Thanks.
